### ISSUE TITLE
Unable to connect k8s master. Aborting

### ISSUE THREAD

**Issue by abriko** [kubeup/hostroutes#2]
on all nodes hostroutes display error:

> F0620 05:18:26.953586       1 main.go:97] Unable to connect k8s master. Aborting
goroutine 1 [running]:
kubeup.com/hostroutes/vendor/github.com/golang/glog.stacks(0x1c53700, 0xc400000000, 0x51, 0x81)
	/home/ubuntu/.go_workspace/src/kubeup.com/hostroutes/vendor/github.com/golang/glog/glog.go:766 +0xa5
kubeup.com/hostroutes/vendor/github.com/golang/glog.(*loggingT).output(0x1c334a0, 0xc400000003, 0xc42018d5c0, 0x1bcef53, 0x7, 0x61, 0x0)
	/home/ubuntu/.go_workspace/src/kubeup.com/hostroutes/vendor/github.com/golang/glog/glog.go:717 +0x337
kubeup.com/hostroutes/vendor/github.com/golang/glog.(*loggingT).printf(0x1c334a0, 0x3, 0x144e8d8, 0x26, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/kubeup.com/hostroutes/vendor/github.com/golang/glog/glog.go:655 +0x14c
kubeup.com/hostroutes/vendor/github.com/golang/glog.Fatalf(0x144e8d8, 0x26, 0x0, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/kubeup.com/hostroutes/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/home/ubuntu/.go_workspace/src/kubeup.com/hostroutes/main.go:97 +0x790

node info:
>kubectl get nodes
NAME                  STATUS                     AGE       VERSION
n1.cluster.xs   Ready,SchedulingDisabled   9m        v1.6.1+coreos.0
n2.cluster.xs   Ready                      6m        v1.6.1+coreos.0
n3.cluster.xs   Ready                      5m        v1.6.1+coreos.0

>kubectl get pods 
NAME              READY     STATUS             RESTARTS   AGE
hostrouts-1cs0c   0/1       CrashLoopBackOff   7          13m
hostrouts-1nk3z   0/1       CrashLoopBackOff   7          14m
hostrouts-3zzmq   0/1       CrashLoopBackOff   7          17m

>kubectl get ds   
NAME        DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR   AGE
hostrouts   3         3         0         3            0           <none>          3h

and k8s version:

> {
  "major": "1",
  "minor": "6",
  "gitVersion": "v1.6.1+coreos.0",
  "gitCommit": "9212f77ed8c169a0afa02e58dce87913c6387b3e",
  "gitTreeState": "clean",
  "buildDate": "2017-04-04T00:32:53Z",
  "goVersion": "go1.7.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}

**Comment by adieu** [comment]
@HuPonya Can you post the result of `kubectl get pods --namespaces kube-system` for me?

It looks like hostroutes cannot connect to the `kubernetes` service in the cluster.

**Comment by abriko** [comment]
@adieu 
> kubectl get pods --namespace kube-system                                                                                                                             NAME                                          READY     STATUS    RESTARTS   AGE
aliyun-controller-n1.cluster.xs         1/1       Running   9          47m
kube-apiserver-n1.cluster.xs            1/1       Running   6          47m
kube-controller-manager-n1.cluster.xs   1/1       Running   4          47m
kube-proxy-n1.cluster.xs                1/1       Running   4          47m
kube-proxy-n2.cluster.xs                1/1       Running   6          44m
kube-proxy-n3.cluster.xs                1/1       Running   4          43m
kube-scheduler-n1.cluster.xs            1/1       Running   4          47m

**Comment by adieu** [comment]
I didn't see `kube-dns` running in `kube-system` namespace. Without `kube-dns`, pods cannot resolve the service names to ip addresses. Maybe that's the cause of this issue.

BTW, I saw `aliyun-controller` running, so maybe you're running the cluster in aliyun. In that case, `hostroutes` wouldn't work properly even if it could setup host routes correctly on the nodes due to limitations in aliyun vpc.

I would suggest that to use our `https://github.com/kubeup/kube-aliyun` project which could setup routes in the vpc for clusters less than 50 nodes.

Feel free to let me know if you need any help making the cluster running.

**Comment by abriko** [comment]
Thanks for the reply! I will try kube-dns.

**Comment by adieu** [comment]
You're welcome. I'll leave this issue open for future updates.

**Comment by abriko** [comment]
You are right. after kube-dns up. **kubernetes** no longer print error messages.
But kubernetes running on master still print...
#1 I looked this issue but my apiserver is not behind SLB...

**Comment by adieu** [comment]
Did you get the cluster running? #1 only applies to clusters with HA master configured. I think it has nothing to do with your issue. Can you check the `kube-proxy` log running in master? And also `iptables` rules. It looks like there're connection issues to k8s services.

**Comment by abriko** [comment]
Thanks you! problem solved.
