### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by pikeszfish** [kubeup/hostroutes#3]
hostroutes 只是个单机软件. 我最近写了个 [pikeszfish/simplest-cni](https://github.com/pikeszfish/simplest-cni)  里面参考了部分/许多 kubeup/hostroutes 的实现. 并将其实现/扩展为 k8s 下的 CNI.

因为没能看到 kubeup/hostroutes 的许可证, 也不是十分了解 kubeup 这个组织, 我在项目中用了 GNU General Public License v3.0.  Is that cool?

**Comment by ledzep2** [comment]
欢迎自由参考. 有mention更好.
